kubernetes-sigs/custom-metrics-apiserver

glide.lock
glide.yaml
pkg/dynamicmapper/fake_discovery.go
pkg/dynamicmapper/mapper.go
pkg/dynamicmapper/mapper_test.go
pkg/provider/errors.go
pkg/provider/interfaces.go
pkg/provider/interfaces_test.go
pkg/sample-cmd/provider/provider.go
pkg/sample-cmd/server/start.go

This commit backports a bunch of generic functionality from https://github.com/directxman12/k8s-prometheus-adapter, including:
- An updating REST mapper
- a function to "normalize" metric info across slightly different resource names
- error constructors for missing metrics

Backport generic functionality from directxman12/k8s-prometheus adapter

---

.travis.yml
glide.lock
glide.yaml
pkg/apiserver/apiserver.go
pkg/apiserver/cmapis.go
pkg/apiserver/installer/apiserver_test.go
pkg/apiserver/installer/installer.go
pkg/apiserver/installer/installer_test.go
pkg/dynamicmapper/fake_discovery.go
pkg/dynamicmapper/mapper_test.go
pkg/provider/interfaces_test.go
pkg/sample-cmd/provider/provider.go
pkg/sample-cmd/server/start.go

This commit updates the deps for Kubernetes 1.8, and makes the
corresponding necessary changes to the actual code (including some
shuffling of fields and accounting for api.Registry being gone).

Updates deps for Kubernetes 1.8

---

pkg/sample-cmd/server/start.go

Fixed typo: objet -> object

---

pkg/cmd/server/start.go

With the update to 1.10, the API server code requires loopback client
setup.  This isn't noted until you actually go to run the server and it
fails, and thus it was missed in the last PR.
Fixes #17

Populate Loopback Options

---

README.md

Running the original curl command will end up with the following error due to the provider expecting json data payload:
` [ServiceError:400] Unable to unmarshal content of type:application/x-www-form-urlencoded`
Adding the `Content-Type: application/json` header fixed the problem.

Updated instruction to use json for data.

---

test-adapter-deploy/testing-adapter.yaml

This patch improve yaml file based on:
- The image name in yaml file is conflict with the one in make file. 
-    Add `imagePullPolicy: IfNotPresent` to avoid pull action when user didn't push their image to remote docker registry. It is helpful especially when it comes to fresh users who have limited knowledge about k8s/docker

Fix an yaml file error which could cause image pull failure

---

pkg/apiserver/cmapis.go
test-adapter-deploy/README.md
test-adapter-deploy/testing-adapter.yaml

Currently only v1beta1 version of an API is exposed.
This change exposes also v1beta2 version of an API.

Expose v1beta2 version of an API

---

go.mod

The go version direction in the `go.mod` file should not contain the minor version number. It specifies a format associated with one version of _go_ and does not change with minor versions. If specified this project cannot be used as a dependency because it gives the following error:
```
go: github.com/kubernetes-incubator/custom-metrics-apiserver@v0.0.0-20200318092248-e409b1073fa9: parsing go.mod: go.mod:3: usage: go 1.23
```

Fixed format of go.mod file for go version

---

test-adapter/generated/openapi-gen.go

Improve the toolchain from https://github.com/kubernetes-sigs/custom-metrics-apiserver/pull/75 to really skip the stub file and use a different build tag as ignore is special https://github.com/golang/go/issues/29598

Fix golang build tag and make change detection

---

pkg/cmd/builder.go
pkg/cmd/server/start.go

Audit logs can be very helpful when debugging requests coming to the
metrics server. They provide insights on the requested resources as well
are information on the user that sent the requests. This is helpful when
trying to narrow down applications spamming the server. Also, we can
configure the audit logs to provide even more information such as the
content of the response which is very helpful when trying to introspect
incorrect data.
/cc @s-urbaniak @fpetkovski

Allow users to configure audit logs

---

Makefile
docs/getting-started.md
go.mod
pkg/apiserver/apiserver.go
pkg/apiserver/cmapis.go
pkg/apiserver/emapis.go
pkg/apiserver/endpoints/handlers/get.go
pkg/apiserver/installer/apiserver_test.go
pkg/apiserver/installer/cmhandlers.go
pkg/apiserver/installer/installer.go
pkg/cmd/builder.go
pkg/cmd/server/start.go
pkg/provider/helpers/helpers.go
pkg/registry/custom_metrics/reststorage.go
pkg/registry/external_metrics/reststorage.go
test-adapter/main.go
test-adapter/provider/provider.go

Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>

chore: use sigs.k8s.io instead of github.com/kubernetes-sigs to refer go pkgs

---

README.md

This pr is used to fix  kubectl proxy port from 8080 to 8001 in README.md

Fix kubectl proxy port from 8080 to 8001

---

docs/getting-started.md
test-adapter-deploy/README.md

This PR updates the Getting Started guide, in particular:
- use up-to-date metric API interfaces
- fix naming consistence

Update and fix Getting Started guide

---

pkg/cmd/builder.go
pkg/generated/openapi/core/zz_generated.openapi.go

Add default `Info.Version` to OpenAPI config (cf #110), which may be required.
Also regenerate OpenAPI defintions for v1.

Add default Info.Version to OpenAPI config

---

README.md
test-adapter-deploy/testing-adapter.yaml

- Update README, mention external metrics
- In test-adapter manifest, add `APIService` for external metrics

Update README, mention external metrics

---

pkg/registry/custom_metrics/reststorage.go
pkg/registry/external_metrics/reststorage.go

In two files, package `k8s.io/apiserver/pkg/endpoints/request` was imported twice (both as `request` and `genericapirequest`).
That was surprisingly not reported by golangci-lint.
/kind cleanup

Remove duplicated import

---

test-adapter-deploy/Dockerfile
test-adapter-deploy/testing-adapter.yaml
test-adapter/main.go

Instead of using `klog.InitFlags()` to add logging flags to Go `flags.FlagSet`, then adding them to `github.com/spf13/pflag.FlagSet`, we directly add them to `github.com/spf13/pflag.FlagSet`.
Also, remove deprecated flag `--logtostderr=true` from test-adapter's Dockerfile and manifest.
The flag is still accepted, but [is deprecated and will soon be removed](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components); as `true` is its default value, removing the flag from the manifest does not break things.
/kind cleanup

test-adapter: refactor adding logging flags

---

.gitignore
pkg/cmd/builder.go
pkg/cmd/options/options.go
pkg/cmd/options/options_test.go

- Adds option validation
- <s>Apply `Features` flags (related to profiling): they were defined but unused</s>
- <s>Adds the possibility to disable the APIServer's own metrics (however, I did not add a flag for that)</s>
- Improve code documentation and add tests
Note: this breaks the API compatibility by:
- removing `CustomMetricsAdapterServerOptions.Complete`
- changing `CustomMetricsAdapterServerOptions.Validate` from `func([]string) error` to `func() error`
However, these two functions were empty, so probably unused by downstream implementations. Do you still prefer if I keep the API compatibility ?
/kind feature

Improve options handling

---

Makefile
go.mod
go.sum
hack/tools.go
pkg/dynamicmapper/mapper.go

- Add missing license header
- Add license checker (was suggested in [this recent PR comment](https://github.com/kubernetes-sigs/custom-metrics-apiserver/pull/110#discussion_r1029227366) - inspired by what metrics-server uses)

Add license checker

---

pkg/cmd/options/options.go

The flags "profiling" and "contention-profiling", provided by FeatureOptions, are already added by custom-metrics-apiserver, but were not applied.

Apply Features flags (related to pprof)

---

pkg/cmd/builder.go

related to https://github.com/kubernetes-sigs/custom-metrics-apiserver/issues/105
add qps/burst flag for k8s client, in order to avoid frequent client-side throttle in some scenarios.

add qps/burst flag for k8s client, and provide method to hide these flags

---

pkg/cmd/options/options.go

By setting `EnableMetrics` to false, it will be possible to disable the API server's own instrumentation metrics.

Adds the option to disable APIServer's own metrics

---

pkg/apiserver/metrics/metrics.go
pkg/apiserver/metrics/metrics_test.go
pkg/registry/custom_metrics/reststorage.go
pkg/registry/external_metrics/reststorage.go
test-adapter/main.go
test-adapter/provider/provider.go

Add a metric `custom_metrics_apiserver_metric_freshness_seconds`, similar to the [metric `metrics_server_api_metric_freshness_seconds` from metrics-server](https://github.com/kubernetes-sigs/metrics-server/blob/a8299de9be086b0cf787ba2c713d117c2f82b5d0/pkg/api/monitoring.go#L22-L30).
This metric can optionally be registered using `RegisterMetrics(registrationFunc func(metrics.Registerable) error) error`, e.g:
```go
metrics.RegisterMetrics(legacyregistry.Register)
```
Also, in test-adapter:
- register the new metric `custom_metrics_apiserver_metric_freshness_seconds`;
- currently, the timestamp for custom metrics values is the time when the metric is queried. With this change, the timestamp used is the time when the metric value is created / updated.

Add metric about metrics freshness

---

go.mod
go.sum

Cf. https://pkg.go.dev/vuln/GO-2022-1144

Bump golang.org/x/net to v0.4.0 for GO-2022-1144

---

Makefile

Currently, running `make test-adapter-container` leaves the `testing-adapter.yaml` file modified.

Makefile: do not mutate manifest file

---

Makefile

PR #143 shows that CI does not fail when OpenAPI definitions generated files are not updated.
I use `touch` on `go.mod` to make sure `make verify` always generate files. I recognize it is not very elegant, but I wanted to keep `make build-test-adapter` run the generation only if needed...
I can use only PHONY targets if you prefer...

Verify generated files in "make verify"

---

pkg/cmd/builder.go
pkg/cmd/options/options.go

Add support for OpenAPI v3
Cf the [implementation in sample-apiserver](https://github.com/kubernetes/kubernetes/blob/3f05d41a416433f3ff90a94edea1f4f876faf132/staging/src/k8s.io/sample-apiserver/pkg/cmd/server/start.go#L144-L148)
/kind feature

Add support for OpenAPI v3

---

test-adapter-deploy/testing-adapter.yaml

Adding `--cert-dir=<a temp directory>` enables the container to be executed as non-root (cf #107)
Adding it to the test-adapter should serve as an example for custom-metrics-apiserver implementations.

test-adapter: add --cert-dir to manifest

---

docs/getting-started.md
pkg/apiserver/installer/apiserver_test.go
pkg/provider/defaults/default_metric_providers.go
pkg/provider/fake/fake.go
pkg/provider/interfaces.go
test-adapter/provider/provider.go

Signed-off-by: Jorge Turrado <jorge_turrado@hotmail.es>
Fixes https://github.com/kubernetes-sigs/custom-metrics-apiserver/issues/150

feat: add default implementation for providers

---

pkg/apiserver/endpoints/handlers/get.go
pkg/registry/custom_metrics/reststorage.go

Currently, the invalid custom metric request `/apis/custom.metrics.k8s.io/v1beta2/namespaces/default/foo` causes a **panic** of the adapter implementing `custom-metrics-apiserver` instead of a normal failure.
```
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta2/namespaces/default/foo"
```
The panic is caused by the error `runtime error: slice bounds out of range [2:1]` here:
https://github.com/kubernetes-sigs/custom-metrics-apiserver/blob/e15f12bf86a01ad500cdc1df2a1359ebbf852000/pkg/apiserver/endpoints/handlers/get.go#L146
In that case, `/namespaces/default/foo` has three parts so it is handled as a **root** resource metric (`/resource/name/subresource`). However, the API server `RequestInfoResolver` handles the request as a **namespaced** resource request, and [removes the …

Fix panic for some invalid custom metric requests

---

docs/metrics-ref.md

This adds a reference doc for metrics exposed by this component. Mostly generated using tooling from k/k.
I can check in the scripts if necessary but it's a bit hacky -- modified the tools [here](https://github.com/kubernetes/kubernetes/pull/113343) and essentially use this [file](https://github.com/kubernetes/kubernetes/blob/master/test/instrumentation/documentation/documentation-list.yaml) as a lookup table for the scraped metrics. This is because the static analysis tool does not identify metrics defined in dependencies (most of the metrics exposed by the custom metrics adapter).
Closes https://github.com/kubernetes-sigs/custom-metrics-apiserver/issues/134

Docs: Add partially generated metrics reference

---

pkg/cmd/options/options.go
test-adapter-deploy/testing-adapter.yaml

Disable priority and fairness by default because the metric APIs are not meant to be interacted with directly but rather by going through the kube-apiserver where the P&F config should reside. In the eventually that some users ever need to enable P&F at the metric server level, they will still be able to do it via the `--enable-priority-and-fairness` flag.

Disable priority and fairness by default

---

OWNERS

Based on the discussion I had on Slack with @richabanker and @rexagod, we agreed that the project needs more care and it would be in everyone's best interest to empower some of its main consumers to keep the project up-to-date.
To achieve that goal I updated the OWNERS file and added @RainbowMango (Kamarda) as an approver.

ONWERS: add RainbowMango

---

.golangci.yml
Makefile
go.mod

Update golangci-lint to a version built with golang 1.24.
The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since
Go1.22 (loopvar) this linter is no longer relevant. Replaced by
copyloopvar.

chore: bump go to 1.24.2

---

README.md

Add a hint that there is already a make target for local test setup.
It is just a small thing but makes it easier for future contributors to get started.

docs: update README with local test instructions
